from flask import Blueprint, request, jsonify
from flask_login import login_required, current_user
from app.models import ResearchStudy, StudyParticipant, ResearchDataPoint, db
from datetime import datetime
import uuid

research_bp = Blueprint('research', __name__)

@research_bp.route('/studies', methods=['GET'])
def get_studies():
    """List all available research studies"""
    # In production, filter by status='active' or user permissions
    studies = ResearchStudy.query.all()
    return jsonify([{
        'id': s.id,
        'title': s.title,
        'description': s.description,
        'status': s.status,
        'start_date': s.start_date.isoformat() if s.start_date else None
    } for s in studies])

@research_bp.route('/studies/<study_id>/enroll', methods=['POST'])
@login_required
def enroll_participant(study_id):
    """Enroll current user in a study"""
    data = request.json
    
    # Check if study exists and is active
    study = ResearchStudy.query.get_or_404(study_id)
    if study.status != 'active':
        return jsonify({'error': 'Study is not active'}), 400
        
    # Check if already enrolled
    existing = StudyParticipant.query.filter_by(
        study_id=study_id, 
        original_user_id=current_user.id
    ).first()
    
    if existing:
        return jsonify({'error': 'Already enrolled'}), 400
        
    # Create participant record
    participant = StudyParticipant(
        id=str(uuid.uuid4()),
        study_id=study_id,
        participant_id=data.get('participant_id'), # Generated by frontend
        original_user_id=current_user.id,
        study_arm=data.get('study_arm'),
        consent_signed_at=datetime.utcnow(),
        consent_version=data.get('consent_version'),
        demographics=data.get('demographics') # Anonymized demographics
    )
    
    db.session.add(participant)
    db.session.commit()
    
    return jsonify({
        'message': 'Successfully enrolled',
        'participant_id': participant.participant_id
    })

@research_bp.route('/studies/<study_id>/data', methods=['POST'])
def submit_data(study_id):
    """Submit anonymized research data point"""
    # Note: This endpoint might not require login if using participant_id auth token
    # For now, we assume frontend provides participant_id and we validate it
    
    data = request.json
    participant_id = data.get('participant_id')
    
    participant = StudyParticipant.query.filter_by(
        study_id=study_id,
        participant_id=participant_id
    ).first_or_404()
    
    if participant.withdrawn:
        return jsonify({'error': 'Participant withdrawn'}), 400
        
    data_point = ResearchDataPoint(
        study_id=study_id,
        participant_id=participant.id, # Internal DB ID
        data_type=data.get('data_type'),
        acoustic_features=data.get('acoustic_features'),
        metadata=data.get('session_metadata')
    )
    
    db.session.add(data_point)
    db.session.commit()
    
    return jsonify({'message': 'Data received'})

@research_bp.route('/studies/<study_id>/withdraw', methods=['POST'])
def withdraw_participant(study_id):
    """Withdraw from a study"""
    data = request.json
    participant_id = data.get('participant_id')
    
    participant = StudyParticipant.query.filter_by(
        study_id=study_id,
        participant_id=participant_id
    ).first_or_404()
    
    participant.withdrawn = True
    participant.withdrawal_reason = data.get('reason')
    
    # Handle data retention policy here (e.g. delete data if requested)
    if data.get('delete_data'):
        ResearchDataPoint.query.filter_by(participant_id=participant.id).delete()
        
    db.session.commit()
    
    return jsonify({'message': 'Withdrawn successfully'})
