"""Initial

Revision ID: 401e94a95ae2
Revises: 
Create Date: 2025-11-30 13:28:00.118886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401e94a95ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mood', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_column('client_id')
        batch_op.drop_column('tags')
        batch_op.drop_column('mood')

    # ### end Alembic commands ###
