"""Add journal user client index

Revision ID: 502f95b96bf3
Revises: 401e94a95ae2
Create Date: 2025-05-22 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502f95b96bf3'
down_revision = '401e94a95ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.create_index('idx_journal_user_client', ['user_id', 'client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_index('idx_journal_user_client')

    # ### end Alembic commands ###
